[package]
authors = ["Walfie <walfington@gmail.com>"]
name = "crabigator"
version = "0.1.0"

[dependencies]
error-chain = "0.10"
futures = "0.1"
hyper = "0.11"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

[dev-dependencies]
tokio-core = "0.1"
hyper-tls = "0.1"
